jasypt:
  encryptor:
    password: f5088fe56cb8447aa56fe7db9e3b2444 # salt 盐值，需要和加密时使用的 salt 一致
    algorithm: PBEWithMD5AndDES # 加密算法，需要和加密时使用的算法一致
    string-output-type: base64 # 密文格式，，需要和加密时使用的输出格式一致

spring:
  datasource:
#    TODO 给密码进行加密
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/melon?serverTimezone=UTC
      username: root
      password: ENC(wq1/SxWGmYPgSS2HuLdUbTjVb4tAZRkN)
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

#开启驼峰式命名规则自动转换
mybatis:
  configuration:
    map-underscore-to-camel-case: true


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true #开启驼峰式命名规则自动转换
    jdbc-type-for-null: "null"
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 日志配置
logging:
  level:
    root: info
    # 事务日志
    org.springframework.transaction: debug
    org.springframework.jdbc.support.JdbcTransactionManager: debug
    # 项目日志路径
    com.example: debug
